### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tonyhayes** [raineroviir/react-redux-socketio-chat#47]
I've just installed and I'm having a problem running; Can you suggest anything that I may not have done?

Anthonys-MacBook-Pro:react-redux-socketio-chat tony$ npm run dev

> React-redux-socketio-chat@0.7.1 dev /Users/tony/react-redux-socketio-chat
> node src/server/server

module.js:338
    throw err;
    ^
Error: Cannot find module 'history'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (server.dev.js:14:1)
    at Module._compile (module.js:460:26)
    at loader (/Users/tony/react-redux-socketio-chat/node_modules/babel-core/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tony/react-redux-socketio-chat/node_modules/babel-core/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tony/react-redux-socketio-chat/src/server/server.js:5:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! React-redux-socketio-chat@0.7.1 dev: `node src/server/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the React-redux-socketio-chat@0.7.1 dev script 'node src/server/server'.
npm ERR! This is most likely a problem with the React-redux-socketio-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/server/server
npm ERR! You can get their info via:
npm ERR!     npm owner ls React-redux-socketio-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tony/react-redux-socketio-chat/npm-debug.log

**Comment by tonyhayes** [comment]
never mind - installed history manually via npm
