### ISSUE TITLE
Issue while deploying to heroku. 

### ISSUE THREAD

**Issue by iamnumberten** [raineroviir/react-redux-socketio-chat#57]
My mongodb setup in server.prod.js is 
process.env.MONGODB_URI = process.env.MONGODB_URI || 'mongodb://username:password@ds111771.mlab.com:11771/databasename'; and mongodb couldn't still connect.
Any tips for heroku deployment?

**Comment by raineroviir** [comment]
I would recommend adding the mongoDB URI through the command  `heroku addons:create mongolab`.

Thats how I created it originally for my production heroku app.
More info at this link: https://devcenter.heroku.com/articles/mongolab

**Comment by iamnumberten** [comment]
Thank you for your reply, Do you mean to suggest that i should not update server.prod.js leaving process.env.MONGOLAB_URI = process.env.MONGOLAB_URI || 'mongodb://localhost/chat_dev'; as same and try to add mongodb through command?

**Comment by iamnumberten** [comment]
My heroku logs error=
2017-04-20T22:28:18.494837+00:00 heroku[web.1]: Starting process with command `npm start`
2017-04-20T22:28:21.454800+00:00 app[web.1]: 
2017-04-20T22:28:21.454848+00:00 app[web.1]: > React-redux-socketio-chat@0.7.1 start /app
2017-04-20T22:28:21.454850+00:00 app[web.1]: > NODE_ENV=production node src/server/server
2017-04-20T22:28:21.454850+00:00 app[web.1]: 
2017-04-20T22:28:28.495861+00:00 heroku[web.1]: State changed from starting to up
2017-04-20T22:28:28.498887+00:00 app[web.1]: server listening on port: 7507
2017-04-20T22:28:28.525070+00:00 app[web.1]: { MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
2017-04-20T22:28:28.525073+00:00 app[web.1]:     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:327:35)
2017-04-20T22:28:28.525077+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-04-20T22:28:28.525078+00:00 app[web.1]:     at Pool.emit (events.js:188:7)
2017-04-20T22:28:28.525079+00:00 app[web.1]:     at Connection.g (events.js:291:16)
2017-04-20T22:28:28.525078+00:00 app[web.1]:     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:274:12)
2017-04-20T22:28:28.525080+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-04-20T22:28:28.525080+00:00 app[web.1]:     at Connection.emit (events.js:191:7)
2017-04-20T22:28:28.525081+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:177:49)
2017-04-20T22:28:28.525081+00:00 app[web.1]:     at Socket.g (events.js:291:16)
2017-04-20T22:28:28.525082+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-04-20T22:28:28.525083+00:00 app[web.1]:     at Socket.emit (events.js:188:7)
2017-04-20T22:28:28.525083+00:00 app[web.1]:     at emitErrorNT (net.js:1281:8)
2017-04-20T22:28:28.525084+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
2017-04-20T22:28:28.525085+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:104:9)
2017-04-20T22:28:28.525086+00:00 app[web.1]:   name: 'MongoError',
2017-04-20T22:28:28.525087+00:00 app[web.1]:   message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }

**Comment by raineroviir** [comment]
All you need to do to get this project working on heroku is the following:
`heroku create`
`git push heroku master`

and then do `heroku addons:create mongolab`

Then if you want to access the mongoDB instance provided by mongolab, you can either log into it through heroku.com and use the GUI, or if you want to connect another project to the same instance u can get the mongolab URI through this command `heroku config:get MONGODB_URI`

**Comment by raineroviir** [comment]
I'm going to close this for the time being, feel free to let me know if you were able to fix your issue.  I want to add that your logs show the heroku server attempting to connect to a localhost server which means your config is pointing to the wrong ip address
